USE ChinaMarinetime
GO
INSERT INTO PageInfo (CallNo, BookName, StartTime, EndTime, BookNo, StartPage, EndPage, Condition, Region, Title, Tag, Category, Remark1, Remark2, Composition)
VALUES ('F0265', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 6, 7, N'良好', N'Newchwang', N'No.1', 'M', N'Map', NULL, NULL, NULL),
 ('F0266', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 6, 7, N'良好', N'Newchwang', N'No.2', 'M', N'Map', NULL, NULL, NULL),
 ('F0267', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 6, 7, N'良好', N'Newchwang', N'No.3', 'M', N'Map', NULL, NULL, NULL),
 ('F0268', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 32, 33, N'折元破損', N'Tientsin', N'River Peiho', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0269', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 58, 59, N'破損、折れあり', N'Chefoo', N'Junk Trade', 'M', N'Map', NULL, N'折畳', N'合成'),
('F0270', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 58, 59, N'良好', N'Chefoo', N'Flood', 'M', N'Map', N'1898', N'折畳', NULL),
 ('F0271', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 78, 79, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0272', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 80, 81, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0273', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 82, NULL, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1897-1898', N'折畳', NULL),
 ('F0274', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 96, 97, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0275', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 98, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0276', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 99, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0277', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 119, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0278', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 120, 121, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0279', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 122, 123, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0280', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 124, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0281', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 133, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0282', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 134, 135, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0283', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 136, 137, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0284', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 138, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0285', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 168, 169, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0286', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 170, 171, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0287', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 172, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0288', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 173, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0289', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 191, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0290', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 191, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0291', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 192, 193, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0292', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 194, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0293', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 194, 195, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1897-1898', N'折畳', NULL),
 ('F0294', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 195, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0295', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 212, 213, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0296', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 214, 215, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0297', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 216, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0298', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 501, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0299', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 502, 503, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0300', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 504, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0301', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 505, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0302', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 518, 519, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0303', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 520, 521, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0304', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 522, 523, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0305', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 524, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0306', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 652, 653, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0307', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 654, 655, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0308', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 656, 657, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0309', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 658, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0310', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 678, 679, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0311', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 678, 679, N'折元破損、端折れ', N'Szemao', N'Shan States', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0312', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 680, 681, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0313', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 682, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0314', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 692, 693, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0315', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1898, NULL, 1, 694, 695, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0316', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 8, 9, N'破損修理済', N'Newchwang', N'Manchuria', 'M', N'Map', N'1900', N'折畳', N'合成'),
('F0317', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 30, 31, N'良好', N'Tientsin', N'River Peiho', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0318', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 82, 83, N'破損修理済、端折れそのまま', N'Kiaochow', N'Kiaochow', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0319', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 99, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0320', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 100, 101, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0321', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 102, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0322', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 102, 103, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0323', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 103, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0324', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 116, 117, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0325', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 118, 119, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0326', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 120, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0327', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 139, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0328', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 140, 141, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0329', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 142, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0330', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 143, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0331', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 152, 143, N'両開き、中央に破損あり', N'Yochow', N'Hunan', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0332', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 153, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0333', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 154, 155, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0334', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 156, 157, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0335', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 156, 157, N'良好', N'Yochow', N'Settlement', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0336', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 158, NULL, N'良好', N'Yochow', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F0337', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 160, 161, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0338', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 162, 163, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0339', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 164, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0340', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 194, 195, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0341', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 196, 197, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0342', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 198, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0343', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 217, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0344', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 218, 219, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0345', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 220, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0346', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 220, 221, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1898-1899', N'折畳', NULL),
 ('F0347', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 221, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0348', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 240, 241, N'折元破損、端折れ', N'Nanking', N'Nanking City', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0349', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 244, 245, N'折元破損', N'Nanking', N'Nanking Port', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0350', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 260, 261, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0351', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 262, 263, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0352', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 264, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0353', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 511, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0354', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 512, 513, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0355', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 514, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0356', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 515, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0357', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 532, 533, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0358', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 534, 535, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0359', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 536, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0360', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 709, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0361', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 710, 711, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0362', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 732, 733, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0363', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 732, 733, N'折元破損、端折れ', N'Szemao', N'Yunnan', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0364', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 734, 735, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0365', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 745, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0366', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 746, 747, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0367', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1899, NULL, 1, 748, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0368', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 79, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0369', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 80, 81, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0370', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 82, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0371', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 82, 83, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1899-1900', N'折畳', NULL),
 ('F0372', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 83, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0373', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 98, 99, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0374', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 100, 101, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0375', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 102, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0376', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 119, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0377', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 120, 121, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0378', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 122, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0379', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 123, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0380', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 137, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0381', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 138, 139, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0382', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 138, 139, N'折元破損、端折れ', N'Yochow', N'Yochow Horbour', 'M', N'Map', N'1900', N'折畳', N'合成'),
('F0383', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 140, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0384', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 141, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0385', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 149, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0386', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 150, 151, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0387', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 152, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0388', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 152, 153, N'折元僅かな破損', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1865-1900', N'折畳', NULL),
 ('F0389', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 153, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0390', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 184, 185, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0391', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 186, 187, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0392', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 188, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0393', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 206, 207, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0394', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 208, 209, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0395', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 208, 209, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1899-1900', N'折畳', NULL),
 ('F0396', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 210, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0397', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 249, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0398', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 250, 251, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0399', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 252, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0400', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 253, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0401', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 501, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0402', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 502, 503, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0403', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 504, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0404', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 505, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0405', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 523, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0406', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 524, 525, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0407', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 526, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0408', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 527, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0409', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 697, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0410', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 698, 699, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0411', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 700, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0412', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 701, NULL, N'良好', N'Lungchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0413', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 712, 713, N'角折れ', N'Mengtsu', N'Laokai&Hokow', 'M', N'Map', N'1900', N'折畳', NULL),
 ('F0414', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 724, 725, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0415', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 726, 727, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0416', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 743, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0417', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 744, 745, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0418', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1900, NULL, 1, 746, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0419', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 83, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0420', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 84, 85, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0421', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 86, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0422', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 86, 87, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1900-1901', N'折畳', NULL),
 ('F0423', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 87, NULL, N'良好', N'Chungking', N'Trade Report', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0424', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 102, 103, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0425', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 104, 105, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0426', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 106, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0427', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 123, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0428', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 124, 125, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0429', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 126, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0430', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 127, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0431', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 143, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0432', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 144, 145, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0433', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 146, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0434', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 147, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0435', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 159, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0436', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 160, 161, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0437', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 162, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0438', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 163, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0439', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 194, 195, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0440', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 196, 197, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0441', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 198, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0442', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 217, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0443', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 218, 219, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0444', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 220, 221, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0445', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 221, NULL, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1900-1901', N'折畳', NULL),
 ('F0446', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 263, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0447', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 264, 265, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0448', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 266, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0449', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 267, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0450', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 560, 561, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0451', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 634, 635, N'天破損', N'Canton', N'Lappa,Canton&Kowloon', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0452', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 636, 637, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0453', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 638, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0454', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 659, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0455', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 660, 661, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0456', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 662, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0457', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 663, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0458', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 724, 725, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0459', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 726, 727, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0460', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 728, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0461', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 753, NULL, N'良好', N'Lungchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0462', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 754, 755, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0463', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 756, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0464', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 766, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0465', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 767, NULL, N'破損修理済', N'Tengyueh', N'Tengyueh', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0466', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 770, 771, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0467', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 776, 777, N'良好', N'Tientsin', N'River Peiho', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0468', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1901, NULL, 1, 778, 779, N'良好', N'Tientsin', N'River Peiho', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0469', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 141, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0470', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 142, 143, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0471', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 144, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0472', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 144, 145, N'良好', N'Chungking', N'River Yangtze', 'G', N'1901-1902', NULL, N'折畳', NULL),
 ('F0473', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 145, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0474', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 161, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0475', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 162, 163, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0476', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 164, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0477', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 165, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0478', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 182, 183, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0479', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 184, 185, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0480', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 186, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0481', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 202, 203, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0482', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 204, 205, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0483', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 206, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0484', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 218, 219, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0485', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 220, 221, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0486', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 222, 223, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0487', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 224, 225, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0488', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 224, 225, N'折山、折元、天破損', N'Hankow', N'Plan of Hankow', 'M', N'Map', N'1903', N'折畳', N'合成'),
('F0489', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 226, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0490', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 260, 261, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0491', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 262, 263, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0492', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 264, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0493', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 265, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0494', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 286, 287, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0495', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 288, 289, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0496', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 290, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0497', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 290, 291, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1901-1902', N'折畳', NULL),
 ('F0498', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 291, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0499', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 334, 335, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0500', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 336, 337, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0501', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 338, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0502', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 339, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0503', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 719, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0504', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 720, 721, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0505', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 722, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0506', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 723, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0507', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 745, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0508', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 746, 747, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0509', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 748, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0510', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 749, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0511', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 810, 811, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0512', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 812, 813, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0513', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 814, NULL, N'良好', N'Lungchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0514', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 840, 841, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0515', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 842, 843, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0516', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 866, 867, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0517', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1902, NULL, 1, 868, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL);
 GO