USE ChinaMarinetime
GO
INSERT INTO PageInfo (CallNo, BookName, StartTime, EndTime, BookNo, StartPage, EndPage, Condition, Region, Title, Tag, Category, Remark1, Remark2, Composition)
VALUES ('F7001', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 1, NULL, N'良好', N'Harbin', N'Shanghai Taels-Roubles Rate', 'Ｇ', N'グラフ', N'1911-1916', NULL, NULL),
('F7002', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 206, 207, N'良好', N'Newchwang', N'Bar Mouth of Liao River', 'Ｍ', N'Map', N'1916', NULL, NULL),
 ('F7003', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 336, 337, N'良好', N'Lungkow', N'Lungkow Settlement', 'Ｍ', N'Map', N'1916', N'折畳', NULL),
 ('F7004', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 421, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7005', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 422, 423, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7006', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 424, 425, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7007', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 426, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7008', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 434, 435, N'良好', N'Chungking', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7009', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 436, NULL, N'良好', N'Chungking', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7010', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 445, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7011', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 445, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7012', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 446, 447, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7013', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 448, NULL, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7014', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 455, NULL, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7015', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 456, 457, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7016', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 470, 471, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7017', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 475, NULL, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7018', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 476, 477, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7019', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 510, 511, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7020', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 512, NULL, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7021', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 517, NULL, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7022', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 518, 519, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7023', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 530, 531, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7024', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 532, 533, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7025', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 534, 535, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7026', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 536, 537, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7027', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 538, 539, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7028', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 540, 541, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7029', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 542, NULL, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7030', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 561, NULL, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7031', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 562, 563, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7032', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 623, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7033', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 624, 625, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7034', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 626, 627, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7035', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 628, NULL, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7036', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 638, 639, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7037', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 640, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7038', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 654, 655, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7039', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 656, 657, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7040', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 658, 659, N'良好', N'Wuhu', N'River Yangtze', 'Ｇ', N'グラフ', N'1914-1916', NULL, NULL),
 ('F7041', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 658, 659, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7042', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 660, NULL, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7043', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 672, 673, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7044', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 674, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7045', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 718, 719, N'良好', N'Chinkiang', N'Chinkiang Harbour', 'Ｍ', N'Map', N'1916', N'折畳', NULL),
 ('F7046', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 720, 721, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7047', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 722, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F7048', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 730, 731, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F7049', N'XVIII - F - 7   China Inspectorate general of customs', 1916, NULL, 1, 732, NULL, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL);
 GO