USE ChinaMarinetime
GO
INSERT INTO PageInfo (CallNo, BookName, StartTime, EndTime, BookNo, StartPage, EndPage, Condition, Region, Title, Tag, Category, Remark1, Remark2, Composition)
VALUES ('F1078', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 44, 45, N'折元僅かな破損', N'China', N'Tonnage of Shipping', 'G', N'グラフ', N'1870-1912', N'折畳', N'合成'),
('F1079', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 54, 55, N'良好', N'China', N'Shanghai Taels', 'G', N'グラフ', N'1910-1912', N'折畳', NULL),
 ('F1080', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 249, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1081', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 250, 251, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1082', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 252, 253, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1083', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 254, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1084', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 262, 263, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1085', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 264, 265, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1086', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 266, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1087', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 267, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1088', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 280, 281, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1089', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 282, 283, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1090', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 284, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1091', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 311, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1092', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 321, 313, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1093', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 314, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1094', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 324, 325, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1095', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 326, 327, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1096', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 328, 329, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1097', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 330, 331, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1098', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 332, 333, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1099', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 335, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1100', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 376, 377, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1101', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 378, 379, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1102', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 380, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1103', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 391, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1104', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 392, 393, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1105', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 394, 395, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1106', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 396, 397, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1107', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 396, 397, N'良好', N'Wuhu', N'Anhwei Province', 'M', N'Map', N'1912', NULL, NULL),
 ('F1108', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 398, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1109', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 398, 399, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1910-1912', N'折畳', NULL),
 ('F1110', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 398, 399, N'良好', N'Wuhu', N'Port of Wuhu', 'Ｍ', N'Map', N'1912', N'折畳', NULL),
 ('F1111', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 399, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1112', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 430, 431, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1113', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 430, 431, N'良好', N'Chinkiang', N'Chinkiang Harbour', 'M', N'Map', N'1912', N'折畳', NULL),
 ('F1114', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 432, 433, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1115', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 434, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1116', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 435, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1117', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 781, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1118', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 782, 783, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1119', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 784, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1120', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 792, 793, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1121', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 794, 795, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1122', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 796, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1123', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 855, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1124', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 856, 857, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1125', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 879, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1126', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 880, 881, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1127', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1912, NULL, 1, 888, 889, N'良好', N'Tengyueh', N'Number of Mules', 'G', N'グラフ', N'1903-1910', NULL, NULL),
 ('F1128', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 200, 201, N'良好', N'Newchwang', N'Liao River', 'Ｍ', N'Map', N'1913', NULL, NULL),
 ('F1129', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 200, 201, N'良好', N'Newchwang', N'Newchwang Harbour', 'Ｍ', N'Map', N'1914', NULL, NULL),
 ('F1130', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 202, 203, N'良好', N'Newchwang', N'Yingkow Station', 'Ｍ', N'Map', N'1913', N'折畳', NULL),
 ('F1131', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 368, 369, N'良好', N'Chefoo', N'Chefoo Harbour', 'Ｍ', N'Map', N'1913', NULL, NULL),
 ('F1132', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 433, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1133', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 434, 435, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1134', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 436, 437, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1135', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 438, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1136', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 446, 447, N'良好', N'Chungking', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1137', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 456, 457, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1138', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 458, 459, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1139', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 466, 467, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1140', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 468, NULL, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1141', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 481, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1142', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 482, 483, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1143', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 484, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1144', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 491, NULL, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1145', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 492, 493, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1146', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 529, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1147', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 530, 531, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1148', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 536, 537, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1149', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 538, NULL, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1150', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 549, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1151', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 550, 551, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1152', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 552, 553, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1153', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 554, 555, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1154', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 556, 557, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1155', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 571, NULL, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1156', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 572, 573, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1157', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 646, 647, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1158', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 648, 649, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1159', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 650, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1160', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 658, 659, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1161', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 660, NULL, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1162', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 674, 675, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1163', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 676, 677, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1164', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 676, 677, N'良好', N'Wuhu', N'River Yangtze', 'Ｇ', N'グラフ', N'1911-1913', NULL, NULL),
 ('F1165', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 684, 685, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1166', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 686, NULL, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1167', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 727, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1168', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 728, 729, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1169', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 728, 729, N'良好', N'Chinkiang', N'Chinkiang Harbour', 'Ｍ', N'Map', N'1913', N'折畳', NULL),
 ('F1170', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 730, 731, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1171', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 732, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1172', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 742, 743, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1173', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 744, NULL, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1174', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1317, 1318, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1175', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1319, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1176', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1325, NULL, N'良好', N'Samshui', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1177', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1326, 1327, N'良好', N'Samshui', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1178', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1335, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1179', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1336, 1337, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1180', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1338, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1181', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1346, 1347, N'良好', N'Wuchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1182', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1348, NULL, N'良好', N'Wuchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1183', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1427, NULL, N'天破損', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1184', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1428, 1429, N'天破損', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1185', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1430, NULL, N'天破損', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1186', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1430, 1431, N'角折れ', N'Lungchow', N'River Tsokiang', 'Ｇ', N'グラフ', N'1912-1913', N'折畳', NULL),
 ('F1187', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1436, 1437, N'良好', N'Lungchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1188', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1438, NULL, N'良好', N'Lungchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1189', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1469, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1190', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1913, NULL, 1, 1470, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1191', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 373, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1192', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 374, 375, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1193', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 376, 377, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1194', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 385, NULL, N'良好', N'Chungking', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1195', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 386, NULL, N'良好', N'Chungking', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1196', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 394, 395, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1197', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 396, 397, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1198', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 404, 405, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1199', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 406, NULL, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1200', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 419, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1201', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 420, 421, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1202', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 427, NULL, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1203', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 428, 429, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1204', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 462, 463, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1205', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 464, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1206', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 469, NULL, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1207', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 470, 471, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1208', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 482, 483, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1209', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 482, 483, N'角折れ福耳', N'Hankow', N'Development Scheme of Hankow', 'Ｍ', N'Map', NULL, NULL, NULL),
 ('F1210', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 484, 485, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1211', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 486, 487, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1212', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 488, 489, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1213', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 490, 491, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1214', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 507, NULL, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1215', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 508, 509, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1216', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 566, 567, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1217', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 568, 569, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1218', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 577, NULL, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1219', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 578, 579, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1220', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 592, 593, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1221', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 594, 595, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1222', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 596, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1223', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 596, 597, N'破損、一部分離', N'Wuhu', N'River Yangtze', 'Ｇ', N'グラフ', N'1912-1914', N'折畳', NULL),
 ('F1224', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 605, NULL, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1225', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 606, 607, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1226', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 648, 649, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1227', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 650, 651, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1228', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 650, 651, N'良好', N'Chinkiang', N'Chinkiang Harbour', 'Ｍ', N'Map', N'1914', N'折畳', NULL),
 ('F1229', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 650, 651, N'良好', N'Chinkiang', N'Chinkiang Concession', 'Ｍ', N'Map', N'1914', N'折畳', NULL),
 ('F1230', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 652, 653, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1231', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 664, 665, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1232', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 666, NULL, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1233', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1157, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1234', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1158, 1159, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1235', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1160, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1236', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1168, 1169, N'良好', N'Samshui', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1237', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1170, NULL, N'良好', N'Samshui', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1238', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1178, 1179, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1239', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1180, 1181, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1240', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1188, 1189, N'良好', N'Wuchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1241', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1190, NULL, N'良好', N'Wuchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1242', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1267, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1243', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1268, 1269, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1244', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1274, 1275, N'良好', N'Lungchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1245', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1276, NULL, N'良好', N'Lungchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1246', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1305, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1247', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1914, NULL, 1, 1306, 1307, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1248', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 6, 7, N'破損修理済', N'Harbin', N'Production of Harbin', 'Ｍ', N'Map', N'1915', N'折畳', NULL),
 ('F1249', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 342, 343, N'良好', N'Lungkow', N'Lungkow Harbour', 'Ｍ', N'Map', N'1915', NULL, NULL),
 ('F1250', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 358, 359, N'良好', N'Chefoo', N'Chefoo River', 'Ｍ', N'Map', N'1915', NULL, NULL),
 ('F1251', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 409, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1252', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 410, 411, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1253', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 412, 413, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1254', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 414, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1255', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 426, NULL, N'良好', N'Chungking', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1256', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 424, 425, N'良好', N'Chungking', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1257', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 434, 435, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1258', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 436, 437, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1259', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 444, 445, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1260', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 446, NULL, N'良好', N'Ichang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1261', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 459, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1262', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 460, 461, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1263', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 465, NULL, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1264', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 466, 467, N'良好', N'Shasi', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1265', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 504, 505, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1266', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 506, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1267', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 512, 513, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1268', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 514, NULL, N'良好', N'Yochow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1269', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 524, 525, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1270', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 526, 527, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1271', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 528, 529, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1272', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 530, 531, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1273', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 532, 533, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1274', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 549, NULL, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1275', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 550, 551, N'良好', N'Hankow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1276', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 610, 611, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1277', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 612, 613, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1278', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 614, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1279', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 622, 623, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1280', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 624, NULL, N'良好', N'Kiukiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1281', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 638, 639, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1282', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 640, 641, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1283', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 642, 643, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1284', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 644, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1285', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 644, 645, N'破損修理済', N'Wuhu', N'River Yangtze', 'Ｇ', N'グラフ', N'1913-1915', N'折畳', NULL),
 ('F1286', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 659, NULL, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1287', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 658, 659, N'良好', N'Wuhu', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1288', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 702, 703, N'地破損', N'Chinkiang', N'Chinkiang Harbour', 'Ｍ', N'Map', N'1915', NULL, NULL),
 ('F1289', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 703, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1290', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 704, 705, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1291', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 706, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1292', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 714, 715, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1293', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 716, NULL, N'良好', N'Chinkiang', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1294', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1054, 1055, N'破損修理済', N'Canton', N'High Water Levels of Samshui,Wuchow,Canton', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1295', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1054, 1055, N'良好', N'Canton', N'North River', 'Ｍ', N'Map', N'1915', NULL, NULL),
 ('F1296', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1203, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1297', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1204, 1205, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1298', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1206, 1207, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1299', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1208, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1300', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1220, 1221, N'良好', N'Samshui', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1301', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1222, NULL, N'良好', N'Samshui', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1302', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1230, 1231, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1303', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1232, 1233, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1304', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1240, 1241, N'良好', N'Wuchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1305', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1242, NULL, N'良好', N'Wuchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1306', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1319, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1307', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1242, 1319, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1308', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1320, 1321, N'折れあり', N'Lungchow', N'River Tso-kiang', 'Ｇ', N'グラフ', N'1914-1915', N'折畳', NULL),
 ('F1309', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1320, 1321, N'良好', N'Lungchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1310', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1328, NULL, N'良好', N'Lungchow', N'Shipping', 'Ｇ', N'グラフ', NULL, NULL, NULL),
 ('F1311', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1358, 1359, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1312', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1915, NULL, 1, 1360, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL);
 GO