USE ChinaMarinetime
GO
INSERT INTO PageInfo (CallNo, BookName, StartTime, EndTime, BookNo, StartPage, EndPage, Condition, Region, Title, Tag, Category, Remark1, Remark2, Composition)
VALUES ('F0001', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 57, 60, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0002', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 60, 61, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0003', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 61, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0004', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 105, 108, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0005', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 108, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1881-1882', N'折畳', NULL),
 ('F0006', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 109, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1872-1882', NULL, NULL),
 ('F0007', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 109, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0008', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 121, 124, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0009', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 124, 125, N'天僅かな破損', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1881-1882', NULL, NULL),
 ('F0010', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 125, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0011', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1882, NULL, 1, 142, 145, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0012', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 57, 60, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0013', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 60, 61, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0014', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 61, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0015', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 109, 112, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0016', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 112, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1882-1883', N'折畳', NULL),
 ('F0017', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 113, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1873-1883', NULL, NULL),
 ('F0018', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 113, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0019', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 125, 128, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0020', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 128, 129, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1882-1883', N'折畳', NULL),
 ('F0021', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 129, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0022', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1883, NULL, 1, 147, 149, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0023', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 55, 58, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0024', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 58, 59, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0025', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 59, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0026', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 73, 76, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0027', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 76, 77, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1882-1884', N'折畳', NULL),
 ('F0028', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 77, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0029', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 107, 110, N'良好', N'Kiukiang', N'Trade Report', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0030', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 110, 111, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1883-1884', N'折畳', NULL),
 ('F0031', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 111, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0032', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 123, 126, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0033', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 126, 127, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1883-1884', N'折畳', NULL),
 ('F0034', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1884, NULL, 1, 145, 147, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0035', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 56, 59, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0036', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 56, 57, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0037', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 60, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0038', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 74, 76, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0039', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 76, 77, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0040', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 77, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0041', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 107, 110, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0042', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 110, 111, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1884-1885', N'折畳', NULL),
 ('F0043', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 111, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0044', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 123, 126, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0045', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 126, 127, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1884-1885', N'折畳', NULL),
 ('F0046', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 127, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0047', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1885, NULL, 1, 143, 145, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0048', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 57, 59, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0049', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 58, 59, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1885-1886', N'折畳', NULL),
 ('F0050', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 60, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0051', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 74, 76, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0052', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 76, 77, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1885-1886', N'折畳', NULL),
 ('F0053', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 77, NULL, N'良好', N'Hankow', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F0054', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 107, 109, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0055', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 108, 109, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1885-1886', N'折畳', NULL),
 ('F0056', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 110, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0057', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 126, 129, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0058', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 128, 129, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1885-1886', N'折畳', NULL),
 ('F0059', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 130, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0060', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1886, NULL, 1, 147, 149, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0061', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 60, 63, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0062', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 62, 63, N'地僅かな破損', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1886-1887', N'折畳', NULL),
 ('F0063', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 64, NULL, N'地僅かな破損', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0064', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 78, 81, N'p.79天僅かな破損', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0065', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 80, 81, N'天僅かな破損', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1886-1887', N'折畳', NULL),
 ('F0066', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 82, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0067', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 115, 117, N'天破損あり', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0068', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 116, 117, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1886-1887', N'折畳', NULL),
 ('F0069', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 118, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0070', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 135, 138, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0071', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 138, 139, N'天僅かな破損', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1886-1887', N'折畳', NULL),
 ('F0072', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 139, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0073', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1887, NULL, 1, 157, 159, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0074', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 62, 65, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0075', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 64, 65, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1887-1888', N'折畳', NULL),
 ('F0076', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 66, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0077', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 82, 85, N'82地僅か、83地破損', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0078', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 84, 85, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1887-1888', N'折畳', NULL),
 ('F0079', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 86, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0080', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 119, 121, N'119天破損', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0081', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 120, 121, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1887-1888', N'折畳', NULL),
 ('F0082', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 122, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0083', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 139, 142, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0084', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 142, 143, N'天僅かな破損', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1887-1888', N'折畳', NULL),
 ('F0085', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 143, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0086', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1888, NULL, 1, 161, 163, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0087', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 64, 67, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0088', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 66, 67, N'修理済', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1888-1889', N'折畳', NULL),
 ('F0089', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 68, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0090', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 83, 86, N'地破損', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0091', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 86, 87, N'修理済。天未修理部分あり', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1888-1889', N'折畳', NULL),
 ('F0092', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 87, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0093', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 119, 120, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0094', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 120, 121, N'修理済', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1888-1889', N'折畳', NULL),
 ('F0095', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 121, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0096', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 139, 142, N'141地破損', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0097', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 142, 143, N'天折れと僅かな破損', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1888-1889', N'折畳', NULL),
 ('F0098', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 143, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0099', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 534, 535, N'足を外して修理、封筒入れ', N'Yunnan', NULL, NULL, N'Map', N'1871-1873/1890', N'折畳', N'合成'),
('F0100', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1889, NULL, 1, 162, 164, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0101', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 65, 68, N'65地破損、', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0102', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 68, 69, N'地破損', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1889-1890', N'折畳', NULL),
 ('F0103', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 69, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0104', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 85, 88, N'85天破損、87地破損', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0105', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 88, 89, N'地僅かな破損', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1889-1890', N'折畳', NULL),
 ('F0106', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 89, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0107', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 123, 126, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0108', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 126, 127, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1889-1890', N'折畳', NULL),
 ('F0109', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 127, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0110', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 145, 148, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0111', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 148, 149, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1889-1890', N'折畳', NULL),
 ('F0112', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 149, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0113', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 556, 557, N'外れ図版封筒入れ。修理済', N'Yunnan', NULL, NULL, N'Map', N'1871-1873/1891', N'折畳', N'合成'),
('F0114', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1890, NULL, 1, 168, 169, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0115', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 64, 68, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0116', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 68, NULL, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0117', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 68, 69, N'破損修理。両開き図版、綴じ込まれている。開きに無理がある', N'Szechwan', NULL, 'M', N'Map', N'1891', N'折畳', N'合成'),
('F0118', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 69, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0119', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 78, 81, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0120', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 80, 81, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1890-1891', N'折畳', NULL),
 ('F0121', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 82, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0122', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 100, 103, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0123', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 102, 103, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1890-1891', N'折畳', NULL),
 ('F0124', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 104, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0125', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 138, 141, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0126', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 140, 141, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1890-1891', N'折畳', NULL),
 ('F0127', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 142, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0128', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 162, 165, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0129', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 164, 165, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1890-1891', N'折畳', NULL),
 ('F0130', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 166, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0131', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1891, NULL, 1, 186, 187, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0132', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 64, 67, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0133', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 66, 67, N'前小口僅かな破損、', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1891-1892', N'折畳', NULL),
 ('F0134', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 68, NULL, N'地僅かな破損', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0135', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 77, 79, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0136', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 78, 79, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1891-1892', N'折畳', NULL),
 ('F0137', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 80, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0138', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 97, 100, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0139', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 100, 101, N'地破損', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1891-1892', N'折畳', NULL),
 ('F0140', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 101, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0141', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 136, 139, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0142', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 138, 139, N'地破損', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1891-1892', N'折畳', NULL),
 ('F0143', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 140, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0144', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 160, 163, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0145', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 162, 163, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1891-1892', N'折畳', NULL),
 ('F0146', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 164, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0147', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 184, 185, N'184地破損', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0148', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1892, NULL, 1, 611, 630, N'良好', NULL, N'Appendix I', NULL, NULL, N'Index 1864-92', NULL, NULL),
 ('F0149', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 67, 70, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0150', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 70, 71, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1892-1893', N'折畳', NULL),
 ('F0151', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 71, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0152', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 82, 85, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0153', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 84, 85, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1892-1893', N'折畳', NULL),
 ('F0154', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 86, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0155', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 103, 106, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0156', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 106, 107, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1892-1893', N'折畳', NULL),
 ('F0157', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 107, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0158', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 168, 171, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0159', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 170, 171, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1892-1893', N'折畳', NULL),
 ('F0160', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 172, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0161', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1893, NULL, 1, 194, 195, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0162', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 68, 71, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0163', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 70, 71, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1893-1894', N'折畳', NULL),
 ('F0164', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 72, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0165', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 84, 87, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0166', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 86, 87, N'修理済', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1893-1894', N'折畳', NULL),
 ('F0167', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 88, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0168', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 106, 109, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0169', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 108, 109, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1893-1894', N'折畳', NULL),
 ('F0170', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 110, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0171', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 174, 177, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0172', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 176, 177, N'天地破損', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1893-1894', N'折畳', NULL),
 ('F0173', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 178, NULL, N'地破損', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0174', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1894, NULL, 1, 200, 201, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0175', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 46, 49, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0176', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 48, 49, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1894-1895', N'折畳', NULL),
 ('F0177', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 50, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0178', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 61, 64, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0179', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 64, 65, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1894-1895', N'折畳', NULL),
 ('F0180', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 65, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0181', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 84, 87, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0182', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 86, 87, N'良好', N'Hankow', N'River Yangtze', 'G', N'グラフ', N'1894-1895', N'折畳', NULL),
 ('F0183', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 88, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0184', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 151, 154, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0185', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 154, 155, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1894-1895', N'折畳', NULL),
 ('F0186', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 155, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0187', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1895, NULL, 1, 176, 177, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0188', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 72, 73, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0189', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 74, 75, N'75天僅かな破損', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0190', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 74, 75, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1895-1896', N'折畳', NULL),
 ('F0191', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 76, NULL, N'76天僅かな破損', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0192', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 88, 89, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0193', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 90, 91, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0194', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 92, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0195', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 112, 113, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0196', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 112, 113, N'良好', N'Shasi', N'Route', 'M', N'Map', N'Shasi to Hankow', N'折畳', NULL),
 ('F0197', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 114, 115, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0198', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 116, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0199', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 123, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0200', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 124, 125, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0201', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 126, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0202', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 127, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0203', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 156, 157, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0204', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 158, 159, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0205', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 160, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0206', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 185, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0207', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 186, 187, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0208', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 188, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0209', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 189, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0210', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 206, 207, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0211', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 208, 209, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0212', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1896, NULL, 1, 210, 211, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0213', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 24, 25, N'良好', N'Tientsin', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0214', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 24, 25, N'折元破損、端折れ', N'Tientsin', N'River Peiho', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0215', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 26, 27, N'良好', N'Tientsin', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0216', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 71, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0217', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 72, 73, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0218', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 74, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0219', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 74, 75, N'良好', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1896-1897', N'折畳', NULL),
 ('F0220', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 75, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0221', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 87, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0222', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 88, 89, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0223', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 90, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0224', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 91, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0225', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 111, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0226', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 112, 113, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0227', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 114, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0228', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 115, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0229', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 123, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0230', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 124, 125, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0231', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 126, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0232', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 127, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0233', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 156, 157, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0234', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 158, 159, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0235', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 160, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0236', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 184, 185, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0237', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 186, 187, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0238', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 186, 187, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1896-1897', N'折畳', NULL),
 ('F0239', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 188, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0240', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 206, 207, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0241', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 208, 209, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0242', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 210, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0243', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 334, 335, N'良好', N'Hangchow', N'Settlement', 'M', N'Map', NULL, NULL, NULL),
 ('F0244', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 487, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0245', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 488, 489, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0246', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 490, 491, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0247', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 492, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0248', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 492, 493, N'折元破損、端折れ', N'Wuchow', N'Anchorage', 'M', N'Map', N'1897', N'折畳', NULL),
 ('F0249', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 492, 493, N'良好', N'Wuchow', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F0250', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 493, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0251', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 506, 507, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0252', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 506, 507, N'折元破損、端折れ', N'Samshui', N'Samshui Reach', NULL, N'Map', N'1897', N'折畳', NULL),
 ('F0253', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 508, 509, N'良好', N'Samshui', N'Trade Report', 'M', NULL, NULL, NULL, NULL),
 ('F0254', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 510, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0255', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 632, 633, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0256', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 632, 633, N'折元破損', N'Lungchow', N'Kwangsi', 'M', N'Map', N'1877', NULL, N'合成'),
('F0257', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 634, 635, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0258', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 656, 657, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0259', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 656, 657, N'折元破損、端折れ', N'Szemao', N'Szemao', 'M', N'Map', NULL, NULL, NULL),
 ('F0260', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 658, 659, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0261', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 660, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0262', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 671, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0263', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 672, 673, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0264', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1897, NULL, 1, 674, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL);
 GO