USE ChinaMarinetime
GO
INSERT INTO PageInfo (CallNo, BookName, StartTime, EndTime, BookNo, StartPage, EndPage, Condition, Region, Title, Tag, Category, Remark1, Remark2, Composition)
VALUES ('F0518', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 64, 65, N'端折れ', N'Tientsin', N'River Peiho', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0519', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 156, 157, N'折元破損、小口しわ', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1902-1903', N'折畳', NULL),
 ('F0520', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 157, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0521', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 158, 159, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0522', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 160, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0523', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 161, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0524', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 177, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0525', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 178, 179, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0526', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 180, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0527', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 181, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0528', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 200, 201, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0529', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 202, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0530', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 203, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0531', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 219, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0532', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 220, 221, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0533', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 222, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0534', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 223, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0535', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 240, 241, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0536', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 242, 243, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0537', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 244, 245, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0538', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 246, 247, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0539', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 248, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0540', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 290, 291, N'破損修理済、端折れそのまま', N'Kiukiang', N'Plan of Kiukiang', 'M', N'Map', N'1904', N'折畳', N'合成'),
('F0541', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 291, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0542', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 292, 293, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0543', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 294, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0544', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 295, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0545', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 322, 323, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0546', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 324, 325, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0547', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 324, 325, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1902-1903', N'折畳', NULL),
 ('F0548', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 326, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0549', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 370, 371, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0550', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 372, 373, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0551', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 374, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0552', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 404, 405, N'折元破損、端折れ', N'Shanghai', N'River Yangtze', 'M', N'Map', N'1896', N'折畳', NULL),
 ('F0553', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 404, 405, N'地破損', N'Shanghai', N'Woosung River Entrance', 'M', N'Map', N'1901&1904', N'折畳', NULL),
 ('F0554', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 744, 775, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0555', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 776, 777, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0556', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 778, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0557', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 802, 803, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0558', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 804, 805, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0559', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 806, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0560', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 867, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0561', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 868, 869, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0562', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 870, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0563', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 870, 871, N'良好', N'Lungchow', N'River Tso-Chiang', 'G', N'グラフ', N'1902-1903', NULL, NULL),
 ('F0564', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 871, NULL, N'良好', N'Lungchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0565', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 897, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0566', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 898, 899, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0567', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 900, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0568', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 925, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0569', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1903, NULL, 1, 926, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0570', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 1, NULL, N'破損修理済', N'China', N'Halkwan Tael', 'G', N'グラフ', N'1870-1904', N'折畳', NULL),
 ('F0571', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 16, NULL, N'前小口破損、インク移り', N'China', N'Tonnage of Shipping', 'G', N'グラフ', N'1864-1904', N'折畳', N'合成'),
('F0572', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 12, 13, N'折元破損。付箋なし', N'China', N'Postal Map of China', 'M', N'Mao', N'1904', N'折畳', N'合成'),
('F0573', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 1, NULL, N'折元破損、角端折れ', N'China', N'Halkwan Tael', 'G', N'グラフ', N'1870-1904', N'折畳', NULL),
 ('F0574', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 52, 53, N'角折れ', N'Tientsin', N'Railways&Trade Routes', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0575', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 56, 57, N'良好', N'Tientsin', N'Tientsin Exports', 'G', N'グラフ', N'1895-1904', N'折畳', NULL),
 ('F0576', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 58, 59, N'良好', N'Tientsin', N'Ocean Depth of Taku Bar', 'G', N'グラフ', N'1878-1904', N'折畳', NULL),
 ('F0577', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 60, 61, N'良好', N'Tientsin', N'River Peiho', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0578', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 160, 161, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0579', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 162, NULL, N'地破損', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0580', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 162, 163, N'折元破損', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1903-1904', N'折畳', NULL),
 ('F0581', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 163, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0582', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 182, 183, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0583', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 184, 185, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0584', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 186, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0585', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 207, NULL, N'天破損', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0586', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 208, 209, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0587', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 208, 209, N'良好', N'Shasi', N'Port of shaxi', 'M', N'Map ', NULL, NULL, N'合成'),
('F0588', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 210, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0589', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 211, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0590', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 228, 229, N'良好', N'Changsha', N'Port of Changsha', 'M', N'Map ', N'1904', N'折畳', NULL),
 ('F0591', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 230, 231, N'良好', N'Changsha', N'Changsha', 'M', N'Map ', NULL, N'折畳', NULL),
 ('F0592', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 232, 233, N'折元破損、端折れ', N'Changsha', N'Hunan', 'M', N'Map ', NULL, N'折畳', NULL),
 ('F0593', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 248, 249, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0594', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 250, 251, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0595', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 252, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0596', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 271, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0597', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 272, 273, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0598', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 274, 275, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0599', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 276, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0600', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 277, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0601', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 319, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0602', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 320, 321, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0603', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 322, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0604', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 323, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0605', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 356, 357, N'インクにじみ', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1903-1904', N'折畳', NULL),
 ('F0606', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 357, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0607', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 358, 359, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0608', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 360, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0609', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 360, 361, N'折元破損', N'Wuhu', N'Wuhu City', 'M', N'Map', N'1904', N'折畳', NULL),
 ('F0610', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 361, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0611', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 408, 409, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0612', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 410, 411, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0613', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 412, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0614', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 1, NULL, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0615', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 2, 3, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0616', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 4, 5, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0617', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 6, 7, N'vii～地僅かな破損', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0618', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 8, 9, N'地僅かな破損', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0619', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 10, 11, N'地僅かな破損', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0620', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 12, 13, N'地僅かな破損～xii', N'China', N'Post Office', 'G', N'グラフ', N'1905 Jan', NULL, NULL),
 ('F0621', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 12, 13, N'端折れ', N'China', N'Post Map', 'M', N'Map', N'1904', N'折畳', N'合成'),
('F0622', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 14, NULL, N'良好', N'China', N'Postal Results', 'G', N'グラフ', N'1904', NULL, NULL),
 ('F0623', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 15, NULL, N'良好', N'China', N'Tariff of Postage', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0624', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 16, NULL, N'良好', N'China', N'Tariff of Postage', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0625', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 17, NULL, N'良好', N'China', N'Postage Stamps', NULL, NULL, NULL, NULL, NULL),
 ('F0626', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 18, NULL, N'良好', N'China', N'Postage Stamps', NULL, NULL, NULL, NULL, NULL),
 ('F0627', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 19, NULL, N'良好', N'China', N'Courier Service', NULL, NULL, NULL, NULL, NULL),
 ('F0628', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 830, 831, N'良好', N'Kongmoon', N'Kongmoon', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0629', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 856, 857, N'良好', N'Samshui', N'West River', 'M', N'Map', NULL, NULL, NULL),
 ('F0630', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1904, NULL, 1, 948, 949, N'水損によるインク色移り', N'Lungchow', N'River Tso-Chiang', 'G', N'グラフ', N'1903-1904', N'折畳', NULL),
 ('F0631', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 18, 19, N'良好', N'China', N'Exchange Value', 'G', N'グラフ', N'1903-1905', N'折畳', NULL),
 ('F0632', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 31, NULL, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0633', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 32, 33, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0634', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 34, 35, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0635', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 36, 37, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0636', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 38, 39, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0637', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 40, 41, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0638', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 42, 43, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0639', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 44, 45, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0640', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 46, 47, N'良好', N'China', N'Post Office', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0641', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 48, 49, N'良好', N'China', N'Head and Branch', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0642', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 48, 49, N'折元僅かな破損', N'China', N'Postal Map of China', 'M', N'Map', N'1905', N'折畳', N'合成'),
('F0643', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 50, 51, N'良好', N'China', N'Mail ', 'G', N'グラフ', N'1905', NULL, NULL),
 ('F0644', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 52, NULL, N'良好', N'China', N'Mail ', 'G', N'グラフ', N'1905', NULL, NULL),
 ('F0645', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 53, NULL, N'良好', N'China', N'Mail ', 'G', N'グラフ', N'1904&1905', NULL, NULL),
 ('F0646', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 54, NULL, N'良好', N'China', N'Clubbed Mails', 'G', N'グラフ', N'1905', NULL, NULL),
 ('F0647', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 55, NULL, N'良好', N'China', N'Parcels Received', 'G', N'グラフ', N'1905', NULL, NULL),
 ('F0648', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 56, NULL, N'良好', N'China', N'Parcels Despatched', 'G', N'グラフ', N'1905', NULL, NULL),
 ('F0649', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 57, NULL, N'良好', N'China', N'Parcels In Transit', 'G', N'グラフ', N'1905', NULL, NULL),
 ('F0650', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 58, NULL, N'良好', N'China', N'Summary of Parcels', NULL, NULL, NULL, NULL, NULL),
 ('F0651', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 59, NULL, N'良好', N'China', N'Money order transactions', NULL, NULL, NULL, NULL, NULL),
 ('F0652', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 60, 61, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0653', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 62, 63, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0654', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 64, 65, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0655', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 66, 67, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0656', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 68, 69, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0657', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 70, 71, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0658', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 72, 73, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0659', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 74, NULL, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0660', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 1, NULL, N'良好', N'China', N'Postage Stamps', NULL, N'写真', NULL, NULL, NULL),
 ('F0661', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 2, NULL, N'良好', N'China', N'Postage Stamps', NULL, N'写真', NULL, NULL, NULL),
 ('F0662', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 3, NULL, N'良好', N'China', N'Postage Stamps', NULL, N'写真', NULL, NULL, NULL),
 ('F0663', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 4, NULL, N'良好', N'China', N'Postage Stamps', NULL, N'写真', NULL, NULL, NULL),
 ('F0664', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 32, 33, N'折元破損', N'Tientsin', N'Taku Bar', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0665', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 91, NULL, N'印刷面剥がれ、折元破損', N'Chungking', N'River Yangtze', 'G', N'グラフ', N'1904-1905', N'折畳', NULL),
 ('F0666', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 91, NULL, N'折元、前小口破損', N'Chungking', N'Route Map', 'M', N'Map', NULL, NULL, N'合成'),
('F0667', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 91, NULL, N'前小口、地破損', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0668', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 92, 93, N'地破損', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0669', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 94, 95, N'地破損', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0670', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 96, NULL, N'地破損', N'Chungking', N'Shipping', 'G', N'グラフ', N'1904-1905', N'折畳', NULL),
 ('F0671', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 102, 103, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0672', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 102, 103, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0673', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 104, 105, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0674', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 106, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0675', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 113, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0676', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 114, 115, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0677', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 116, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0678', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 134, 135, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0679', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 136, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0680', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 137, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0681', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 144, 145, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0682', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 146, 147, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0683', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 148, 149, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0684', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 150, 151, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0685', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 152, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0686', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 154, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0687', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 184, 185, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0688', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 186, 187, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0689', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 186, 187, N'折元破損、端折れ', N'Kiukiang', N'Poyang Lake', 'M', N'Map', N'1905', N'折畳', N'合成'),
('F0690', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 188, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0691', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 197, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0692', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 198, 199, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0693', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 198, 199, N'角折れ', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1904-1905', N'折畳', NULL),
 ('F0694', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 200, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0695', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 201, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0696', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 220, 221, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0697', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 222, 223, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0698', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 222, 223, N'良好', N'Chinkiang', N'Chinkiang District', 'M', N'Map', N'1905', N'折畳', NULL),
 ('F0699', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 224, 225, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0700', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 226, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0701', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 384, 385, N'折元破損、角折れ', N'Swatow', N'Railways', 'M', N'Map', NULL, N'折畳', NULL),
 ('F0702', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 470, 471, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0703', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 472, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0704', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 480, 481, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0705', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 482, 483, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0706', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 484, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0707', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 485, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0708', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 514, 515, N'良好', N'Lungchow', N'River Tso-Chiang', 'G', N'グラフ', N'1904-1905', N'折畳', NULL),
 ('F0709', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 515, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0710', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 516, 517, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0711', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 518, NULL, N'良好', N'Lungchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0712', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 535, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0713', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1905, NULL, 1, 536, 537, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0714', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 60, 61, N'良好', N'China', N'Shanghai Taels', 'G', N'グラフ', N'1904', N'折畳', NULL),
 ('F0715', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 65, NULL, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0716', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 66, 67, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0717', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 68, 69, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0718', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 70, 71, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0719', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 72, 73, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0720', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 74, 75, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0721', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 76, 77, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0722', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 78, 79, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0723', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 80, NULL, N'良好', N'China', N'Post Report', NULL, NULL, NULL, NULL, NULL),
 ('F0724', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 81, NULL, N'良好', N'China', N'Post Office', 'G', N'グラフ', N'1904-1906', NULL, NULL),
 ('F0725', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 82, NULL, N'良好', N'China', N'Post Office', 'G', N'グラフ', N'1904-1906', NULL, NULL),
 ('F0726', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 83, NULL, N'良好', N'China', N'Head and Branch', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0727', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 84, 85, N'良好', N'China', N'Head and Branch', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0728', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 84, 85, N'折元破損、端折れ', N'China', N'Postal Map of China', 'M', N'Map', N'1906', N'折畳', N'合成'),
('F0729', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 86, 87, N'良好', N'China', N'Mail ', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0730', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 88, 89, N'良好', N'China', N'Mail ', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0731', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 90, NULL, N'良好', N'China', N'Clubbed Mails', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0732', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 91, NULL, N'良好', N'China', N'Parcels Received', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0733', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 92, NULL, N'良好', N'China', N'Parcels Despatched', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0734', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 93, NULL, N'良好', N'China', N'Parcels In Transit', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0735', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 94, NULL, N'良好', N'China', N'Summary of Parcels', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0736', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 95, NULL, N'良好', N'China', N'Money order transactions', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0737', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 96, NULL, N'良好', N'China', N'Articles', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0738', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 97, NULL, N'前小口破損', N'China', N'Express Letters', 'G', N'グラフ', N'1906', NULL, NULL),
 ('F0739', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 88, NULL, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0740', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 86, 87, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0741', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 84, 85, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0742', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 82, 83, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0743', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 80, 81, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0744', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 78, 79, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0745', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 76, 77, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0746', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 74, 75, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0747', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 72, 73, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0748', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 70, 71, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0749', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 68, 69, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0750', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 66, 67, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0751', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 64, 65, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0752', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 62, 63, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0753', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 60, 61, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0754', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 58, 59, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0755', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 56, 57, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0756', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 54, 55, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0757', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 52, 53, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0758', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 50, 51, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0759', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 48, 49, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0760', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 46, 47, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0761', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 44, 45, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0762', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 42, 43, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0763', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 41, NULL, N'良好', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
 ('F0764', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 89, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0765', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 90, 91, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0766', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 92, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0767', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 93, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0768', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 99, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0769', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 100, 101, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0770', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 102, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0771', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 103, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0772', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 110, 111, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0773', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 112, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0774', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 131, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0775', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 132, 133, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0776', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 134, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0777', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 141, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0778', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 142, 143, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0779', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 144, 145, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0780', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 146, 147, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0781', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 149, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0782', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 180, 181, N'pp.180天角欠損', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0783', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 182, 183, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0784', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 184, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0785', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 192, 193, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1905-1906', N'折畳', NULL),
 ('F0786', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 193, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0787', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 194, 195, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0788', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 196, 197, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0789', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 198, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0790', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 206, 217, N'良好', N'Chinkiang', N'Famine District', 'M', N'Map', N'1906', N'折畳', NULL),
 ('F0791', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 217, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0792', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 218, 219, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0793', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 220, 221, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0794', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 222, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0795', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 230, 231, N'折元破損、角折れ', N'Shanghai', N'Plan of Shanghai Harbour', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0796', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 238, 239, N'良好', N'Shanghai', N'Woosung Bars', 'G', N'グラフ', N'1902-1906', N'折畳', N'合成'),
('F0797', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 238, 239, N'地、折元破損', N'Shanghai', N'Approches to Yangtze', 'M', N'Map', N'1906', N'折畳', N'合成'),
('F0798', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 246, 247, N'折元破損、角折れ', N'Shanghai', N'Whangpoo River Conservancy', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0799', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 246, 247, N'折元破損、角折れ', N'Shanghai', N'Whangpoo River Improvement', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0800', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 382, 383, N'破損修理済', N'Swatow', N'Swatow Customs District', 'M', N'Map', N'1907', N'折畳', N'合成'),
('F0801', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 398, 399, N'折元破損、端折れ', N'Canton', N'Canton Horbour', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0802', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 520, 521, N'良好', N'Lungchow', N'River Tso-Chiang', 'G', N'グラフ', N'1905-1906', N'折畳', NULL),
 ('F0803', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 521, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0804', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 522, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0805', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 540, 541, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0806', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 542, NULL, N'地僅かな破損', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0807', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 548, 549, N'良好', N'Tengyueh', N'Tengyueh District', 'M', N'Map', N'1906', NULL, NULL),
 ('F0808', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 559, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0809', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1906, NULL, 1, 560, 561, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL);
 GO