USE ChinaMarinetime
GO
INSERT INTO PageInfo (CallNo, BookName, StartTime, EndTime, BookNo, StartPage, EndPage, Condition, Region, Title, Tag, Category, Remark1, Remark2, Composition)
VALUES ('F5001', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1869, NULL, 1, 26, 27, N'良好', N'Hankow ', N'Shipping', 'G', N'グラフ', N'1886-1887', NULL, NULL),
 ('F5002', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1869, NULL, 1, 34, 35, N'良好', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5003', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1869, NULL, 1, 35, NULL, N'良好', N'Hankow ', N'Appendix No.5', NULL, NULL, N'Hupeh/Hunan', NULL, NULL),
 ('F5004', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1869, NULL, 1, 42, 43, N'印画紙。修理済', N'Chinkiang', N'Sketch Map', NULL, NULL, NULL, N'印画紙', NULL),
 ('F5005', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1869, NULL, 1, 108, 109, N'良好', N'Tientsin', N'Enclosure', 'G', N'グラフ', N'wind and water', NULL, NULL),
 ('F5006', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1869, NULL, 1, 150, 151, N'印画紙。天破損', N'Kiukiang', NULL, 'M', N'Map', NULL, N'印画紙/片頁撮影', NULL),
 ('F5007', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1869, NULL, 1, 151, 155, N'複写用付箋なし', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5008', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 21, 22, N'良好', N'Hankow ', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5009', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 25, NULL, N'良好', N'Hankow ', N'Native Tea Hongs', NULL, NULL, N'1869-1870', NULL, NULL),
 ('F5010', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 26, 27, N'良好', N'Hankow ', N'Foreign Goods Conveyed', NULL, NULL, NULL, NULL, NULL),
 ('F5011', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 28, NULL, N'良好', N'Hankow ', N'River Yangtze', NULL, NULL, N'1864-1870', NULL, NULL),
 ('F5012', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 28, 29, N'良好', N'Hankow ', N'River Yangtze', NULL, NULL, NULL, N'折畳', NULL),
 ('F5013', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 121, 123, N'良好', N'Swatow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5014', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 131, NULL, N'良好', N'Swatow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5015', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 132, 133, N'良好', N'Swatow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5016', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1870, NULL, 1, 134, 135, N'良好', N'Swatow', NULL, NULL, NULL, NULL, NULL, NULL),
 ('F5017', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 58, 59, N'良好', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5018', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 76, 77, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1871-1872', N'折畳', NULL),
 ('F5019', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 201, NULL, N'良好', N'Swatow', N'Shipping', 'G', N'グラフ', N'1868-1872', NULL, NULL),
 ('F5020', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 206, NULL, N'良好', N'Swatow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5021', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 207, NULL, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5022', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 208, 209, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5023', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 210, 211, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5024', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 212, 213, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5025', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 214, 215, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5026', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 216, 217, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5027', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 218, 219, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5028', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1871, 1872, 1, 220, NULL, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5029', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 31, 33, N'良好', N'Kiukiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5030', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 37, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5031', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 81, NULL, N'良好', N'Ningpo', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5032', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 84, 85, N'良好', N'Ningpo', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5033', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 101, NULL, N'良好', N'Tamsui (Formosa)', N'Junk Trade', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5034', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 102, NULL, N'良好', N'Tamsui (Formosa)', N'Junk Trade', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5035', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 102, 103, N'外れ図版封筒入れ、修理済', N'Tamsui (Formosa)', N'Junk Trade', 'M', N'Map', N'1873', N'折畳', NULL),
 ('F5036', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 146, 147, N'良好', N'Swatow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5037', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1873, NULL, 1, 149, NULL, N'良好', N'Swatow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5038', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 34, NULL, N'良好', N'Hankow ', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5039', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 40, 41, N'良好', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5040', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 51, 53, N'良好', N'Kiukiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5041', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 62, NULL, N'良好', N'Kiukiang', N'List', NULL, NULL, NULL, NULL, NULL),
 ('F5042', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 63, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1868-1874', NULL, NULL),
 ('F5043', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 62, 63, N'片開き4つ折り図版。修理済', N'Kiangsi', N'Foreign Goods Conveyed', 'M', N'Map', N'1874', N'折畳', NULL),
 ('F5044', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 62, 63, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1873-1874', N'折畳', NULL),
 ('F5045', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 75, NULL, N'良好', N'Chinkiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5046', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 105, NULL, N'良好', N'Shanghai', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5047', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 106, 107, N'良好', N'Shanghai', N'Trade Report', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5048', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 108, NULL, N'良好', N'Shanghai', N'Trade Report', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5049', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 118, 119, N'良好', N'Ningpo', N'Foreign Goods Conveyed', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5050', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 120, 121, N'良好', N'Ningpo', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5051', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 129, NULL, N'良好', N'Tamsui (Formosa)', N'Junk Trade', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5052', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 130, 131, N'良好', N'Tamsui (Formosa)', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5053', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 132, 133, N'良好', N'Tamsui (Formosa)', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5054', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 134, 135, N'良好', N'Tamsui (Formosa)', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5055', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 136, 137, N'良好', N'Tamsui (Formosa)', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5056', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 202, 203, N'良好', N'Canton', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5057', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 205, NULL, N'良好', N'Canton', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5058', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1874, NULL, 1, 206, NULL, N'良好', N'Canton', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5059', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 70, 71, N'良好', N'Manchuria', NULL, 'M', N'Map', NULL, N'折畳', NULL),
 ('F5060', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 101, 102, N'良好', N'Hankow ', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5061', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 104, 105, N'良好', N'Hankow ', N'River Yangtze', NULL, NULL, NULL, NULL, NULL),
 ('F5062', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 114, 116, N'良好', N'Kiukiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5063', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 125, 127, N'良好', N'Kiukiang', N'River Yangtze', NULL, NULL, NULL, NULL, NULL),
 ('F5064', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 176, 177, N'良好', N'Ningpo', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5065', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 187, NULL, N'良好', N'Ningpo', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5066', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 218, NULL, N'天僅かな破損', N'Tamsui (Formosa)', N'Appendix No.3', NULL, NULL, NULL, NULL, NULL),
 ('F5067', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 220, NULL, N'良好', N'Tamsui (Formosa)', N'Appendix No.4', NULL, NULL, NULL, NULL, NULL),
 ('F5068', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 220, 221, N'破損。注意札挿入', N'East Coast Of Formosa', NULL, 'M', N'Map', NULL, N'折畳', NULL),
 ('F5069', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 226, 227, N'良好', N'Takow (Formosa)', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5070', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 233, NULL, N'良好', N'Takow (Formosa)', N'Junk Trade', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5071', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 234, 235, N'235天破損', N'Takow (Formosa)', N'Junk Trade', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5072', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 236, 237, N'237天破損', N'Takow (Formosa)', N'Language', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5073', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 238, NULL, N'天僅かな破損', N'Takow (Formosa)', N'Language', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5074', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1875, NULL, 1, 270, 271, N'良好', N'Amoy', N'Shipping', 'G', N'グラフ', N'1874-1875', NULL, NULL),
 ('F5075', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 126, NULL, N'破損修理済、折り方注意付箋入れ', N'China', N'Foreign Goods Conveyed', 'M', N'Map', N'1874', N'折畳', NULL),
 ('F5076', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 126, NULL, N'破損修理済', N'China', N'Foreign Goods Conveyed', 'M', N'Map', N'1875', N'折畳', NULL),
 ('F5077', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 126, NULL, N'破損修理済', N'China', N'Foreign Goods Conveyed', 'M', N'Map', N'1876', N'折畳', NULL),
 ('F5078', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 126, NULL, N'破損修理済', N'China', N'Rates of Exchange', 'G', N'グラフ', N'1871-1876', N'折畳', NULL),
 ('F5079', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 126, NULL, N'破損修理済', N'China', N'Rates of Exchange', 'G', N'グラフ', N'1871-1876', N'折畳', NULL),
 ('F5080', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 126, NULL, N'破損修理済', N'China', N'Mexican Dollars', 'G', N'グラフ', N'1872-1876', N'折畳', NULL),
 ('F5081', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 126, NULL, N'破損修理済', N'China', N'Net Trade', 'G', N'グラフ', N'1867-1876', N'折畳', NULL),
 ('F5082', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 22, 23, N'23隣接ページ、天に僅かな破損あり', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5083', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 32, 33, N'良好', N'Kiukiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5084', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 83, NULL, N'良好', N'Foochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5085', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 84, NULL, N'良好', N'Foochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5086', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 84, 85, N'85隣接ページ破損あり', N'Foochow', N'Sterling Exchange', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5087', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 112, 113, N'良好', N'Amoy', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5088', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 133, NULL, N'良好', N'Amoy', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5089', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 144, 147, N'地に破損あり', N'Swatow', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5090', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 152, 153, N'152地に破損あり', N'Swatow', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5091', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 155, 156, N'良好', N'Canton', N'Shipping', 'G', N'グラフ', N'1867-1876', NULL, NULL),
 ('F5092', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 183, NULL, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5093', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 184, 185, N'良好', N'Canton', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F5094', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1876, NULL, 1, 186, NULL, N'良好', N'Canton', N'Metrical Table ', NULL, NULL, NULL, NULL, NULL),
 ('F5095', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 15, 18, N'15前小口地僅かな破損', N'Hankow ', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5096', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 30, 31, N'良好', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5097', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 32, NULL, N'良好', N'Hankow ', N'Appendix No.3', NULL, NULL, NULL, NULL, NULL),
 ('F5098', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 32, 33, N'良好', N'Hankow ', N'River Yangtze', NULL, N'グラフ', NULL, NULL, NULL),
 ('F5099', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 44, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', NULL, NULL, NULL, NULL),
 ('F5100', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 44, 45, N'修理済', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1876-1877', N'折畳', NULL),
 ('F5101', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 70, 71, N'良好', N'Wuhu', N'Appendix No.2', NULL, NULL, NULL, NULL, NULL),
 ('F5102', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 72, NULL, N'良好', N'Wuhu', N'Appendix No.3', NULL, NULL, NULL, NULL, NULL),
 ('F5103', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 72, 73, N'修理済', N'Wuhu', N'Anhwei', 'M', N'Map', N'1877', N'折畳', NULL),
 ('F5104', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 72, 73, N'修理済', N'Wuhu', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5105', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 142, NULL, N'良好', N'Wenchow', N'Junk Trade', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5106', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 142, 143, N'良好', N'Wenchow', N'Sketch Map', NULL, N'Map', N'1877', N'折畳', NULL),
 ('F5107', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 143, NULL, N'良好', N'Wenchow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5108', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 144, NULL, N'良好', N'Wenchow', N'Metrical Table ', NULL, NULL, NULL, NULL, NULL),
 ('F5109', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 144, 145, N'天地破損', N'Wenchow', N'Survey Map', 'M', N'Map', N'1877', N'折畳', '合成（18のみ）'),
('F5110', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 179, 181, N'？封筒入り地図のことか？179,181の間に図版なし', N'Amoy', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5111', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1877, NULL, 1, 188, NULL, N'良好', N'Amoy', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5112', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 46, 47, N'良好', N'Hankow ', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5113', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 57, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5114', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 58, 59, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5115', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 60, 61, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5116', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 62, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5117', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 62, 63, N'修理済', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5118', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 83, 84, N'良好', N'Kiukiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5119', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 92, 93, N'良好', N'Kiukiang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5120', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 94, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1868-1878', NULL, NULL),
 ('F5121', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 94, 95, N'修理済', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1877-1878', N'折畳', NULL),
 ('F5122', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 104, NULL, N'良好', N'Wuhu', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5123', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 108, NULL, N'良好', N'Wuhu', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5124', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 108, 109, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1877-1878', N'折畳', NULL),
 ('F5125', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1878, NULL, 1, 264, NULL, N'良好', N'Swatow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5126', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 106, 107, N'106地破損', N'China', N'Rates of Exchange', 'G', N'グラフ', N'1878-1879', NULL, NULL),
 ('F5127', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 108, NULL, N'良好', N'China', N'List', NULL, NULL, NULL, NULL, NULL),
 ('F5128', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 108, 109, N'良好', N'China', N'Chart', 'M', N'Map', N'Lights of coast', NULL, NULL),
 ('F5129', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 109, NULL, N'良好', N'China', N'Buoys', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5130', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 110, 111, N'良好', N'China', N'Buoys/Beacons', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5131', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 112, 113, N'良好', N'China', N'Population', NULL, NULL, NULL, NULL, NULL),
 ('F5132', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 114, NULL, N'良好', N'China', N'Population', NULL, NULL, NULL, NULL, NULL),
 ('F5133', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 36, 37, N'良好', N'Hankow ', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5134', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 38, 39, N'良好', N'Hankow ', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5135', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 49, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5136', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 50, 51, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5137', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 52, 53, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5138', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 54, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5139', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 54, 55, N'良好', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5140', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 62, 63, N'良好', N'Kiukiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5141', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 70, 71, N'良好', N'Kiukiang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5142', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 72, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1869-1879', NULL, NULL),
 ('F5143', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 72, 73, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1878-1879', N'折畳', NULL),
 ('F5144', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 92, 93, N'破損修理済み', N'Chinkiang', N'Kiangnan', 'M', N'Map', NULL, N'折畳', NULL),
 ('F5145', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 93, NULL, N'地僅かな破損', N'Chinkiang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5146', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1879, NULL, 1, 228, NULL, N'良好', N'Swatow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5147', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 46, NULL, N'良好', N'Ichang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5148', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 46, 47, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1879-1880', N'折畳', NULL),
 ('F5149', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 52, 55, N'良好', N'Hankow ', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5150', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 67, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5151', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 68, 69, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5152', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 70, 71, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5153', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 72, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5154', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 72, 73, N'良好', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5155', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 76, 77, N'良好', N'Kiukiang', N'Shipping', NULL, NULL, NULL, NULL, NULL),
 ('F5156', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 78, 79, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1879-1880', N'折畳', NULL),
 ('F5157', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 79, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1870-1880', NULL, NULL),
 ('F5158', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 84, 85, N'良好', N'Kiukiang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5159', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 114, NULL, N'良好', N'Chinkiang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5160', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 114, 115, N'破損修理済、折り方注意付箋入れ', N'Chinkiang', N'Kiangnan', 'M', N'Map', NULL, N'折畳', N'合成'),
('F5161', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 210, NULL, N'良好', N'Takow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, N'合成'),
('F5162', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 210, 211, N'外して修理、封筒入れ', N'Takow', N'Formosa', 'M', N'Map', NULL, N'折畳', N'合成'),
('F5163', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 210, 211, N'破損修理済、折り方注意付箋入れ', N'Takow', N'Takow', 'M', N'Map', N'1880', N'折畳', N'合成'),
('F5164', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 230, 231, N'天破損', N'Amoy', N'Southern Fukien', 'M', N'Map', NULL, N'折畳', NULL),
 ('F5165', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 231, NULL, N'良好', N'Amoy', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5166', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1880, NULL, 1, 256, NULL, N'良好', N'Swatow', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5167', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 14, 15, N'良好', N'Ichang', N'River Yangtze', 'G', N'グラフ', N'1880-1881', N'折畳', NULL),
 ('F5168', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 10, 11, N'破損修理済', N'Hankow ', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5169', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 11, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5170', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 12, 13, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5171', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 14, 15, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5172', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 16, NULL, N'良好', N'Hankow ', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5173', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 12, 13, N'良好', N'Kiukiang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5174', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 14, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1871-1881', NULL, NULL),
 ('F5175', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 14, NULL, N'良好', N'Kiukiang', N'River Yangtze', 'G', N'グラフ', N'1880-1881', N'折畳', NULL),
 ('F5176', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 8, 9, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5177', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 12, 13, N'良好', N'Wuhu', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5178', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 26, 27, N'良好', N'Chinkiang', N'River Yangtze', 'G', N'グラフ', NULL, N'折畳', NULL),
 ('F5179', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 27, NULL, N'良好', N'Chinkiang', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5180', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 16, NULL, N'良好', N'Ningpo', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL),
 ('F5181', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 11, NULL, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5182', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 12, 13, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5183', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 14, 15, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5184', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 16, 17, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5185', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 18, 19, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5186', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 20, 21, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5187', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 22, 23, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5188', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 24, 25, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5189', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 26, 27, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5190', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 28, 29, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5191', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 30, 31, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5192', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 32, 33, N'p.33地僅かな破損', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5193', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 34, 35, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5194', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 36, 37, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5195', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 38, NULL, N'良好', N'Tamsui', N'Enclosure', NULL, NULL, NULL, NULL, NULL),
 ('F5196', N'XVIII-F-5 Report on Trade at the treaty ports in China', 1881, NULL, 1, 21, NULL, N'良好', N'Amoy', N'Metrical Table ', 'G', N'グラフ', NULL, NULL, NULL);
 GO