USE ChinaMarinetime
GO
INSERT INTO PageInfo (CallNo, BookName, StartTime, EndTime, BookNo, StartPage, EndPage, Condition, Region, Title, Tag, Category, Remark1, Remark2, Composition)
VALUES ('F0810', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 48, 49, N'良好', N'China', N'Shanghai Taels', 'G', N'グラフ', N'1904', NULL, NULL),
 ('F0811', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 1, NULL, N'良好', N'Antung', N'Antung', 'M', N'Map', N'1907', N'折畳', N'合成'),
('F0812', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 8, 9, N'良好', N'Antung', N'Antung&Shaho', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0813', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 20, 21, N'破損修理済', N'Dairen', N'Kwantung', 'M', N'Map', N'1907', N'折畳', N'合成'),
('F0814', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 24, 25, N'折元破損、端折れ', N'Dairen', N'Plan of Dairen', 'M', N'Map', N'1907', N'折畳', N'合成'),
('F0815', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 137, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0816', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 138, 139, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0817', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 149, 141, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0818', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 142, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0819', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 143, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0820', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 149, NULL, N'地僅かな破損', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0821', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 150, 151, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0822', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 152, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0823', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 153, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0824', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 164, 165, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0825', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 166, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0826', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 167, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0827', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 184, 185, N'折元破損', N'Yochow', N'Plan of Tungting Lake', 'M', N'Map', N'1907', N'折畳', N'合成'),
('F0828', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 185, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0829', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 186, 187, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0830', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 188, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0831', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 189, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0832', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 196, 197, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0833', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 198, 199, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0834', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 200, 201, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0835', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 202, 203, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0836', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 205, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0837', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 236, 237, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0838', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 238, 239, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0839', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 240, 241, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0840', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 242, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0841', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 252, 253, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0842', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 254, 255, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0843', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 256, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0844', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 268, 269, N'折元破損、角折れ', N'Nanking', N'Plan of Nanking', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0845', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 278, 279, N'良好', N'Chinkiang', N'Plan of Yangtze River', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0846', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 279, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0847', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 280, 281, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0848', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 280, 281, N'良好', N'Chinkiang', N'Plan of Chinkiang Harbour', 'M', N'Map', N'1907', N'折畳', NULL),
 ('F0849', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 282, 283, N'p.281～前小口僅かな破損', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0850', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 284, NULL, N'p.281～前小口僅かな破損', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0851', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 308, 309, N'地僅かな破損', N'Shanghai', N'Woosung Bars', 'G', N'グラフ', N'1907', N'折畳', NULL),
 ('F0852', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 308, 309, N'良好', N'Shanghai', N'Whangpoo River Conservancy', 'Ｍ', N'Map', N'1907', N'折畳', NULL),
 ('F0853', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 557, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0854', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 558, 559, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0855', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 560, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0856', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 568, 569, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0857', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 570, 571, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0858', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 572, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0859', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 573, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0860', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 590, 591, N'良好', N'Wuchow', N'West River', 'M', N'Map', N'1907', N'折畳', N'合成'),
('F0861', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 622, 623, N'折元破損、端折れ', N'Lungchow', N'Lungchow Customs District', 'M', N'Map', N'1907', N'折畳', N'合成'),
('F0862', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 623, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0863', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 624, 625, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0864', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 642, 643, N'良好', N'Szemao', N'Szemao District', 'M', N'Map', N'1907', NULL, NULL),
 ('F0865', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 643, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0866', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 644, 645, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0867', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 661, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0868', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1907, NULL, 1, 662, 663, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0869', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 50, 51, N'良好', N'China', N'Shanghai Taels', 'G', N'グラフ', N'1906-1908', N'折畳', NULL),
 ('F0870', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 18, 19, N'折元僅かな破損', N'China', N'Postal Map of China', 'M', N'Map', N'1908', N'折畳', N'合成'),
('F0871', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 64, 65, N'良好', N'Tientsin and Chinwangtao', N'Chinwangtao', 'M', N'Map', N'1908', N'折畳', NULL),
 ('F0872', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 149, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0873', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 150, 151, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0874', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 152, 153, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0875', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 154, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0876', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 160, 161, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0877', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 162, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0878', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 163, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0879', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 174, 175, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0880', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 176, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0881', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 177, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0882', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 198, 199, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0883', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 200, 201, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0884', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 200, 201, N'良好', N'Yochow', N'River Yangtze', 'G', N'グラフ', N'1904-1908', N'折畳', NULL),
 ('F0885', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 202, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0886', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 210, 211, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0887', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 212, 213, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0888', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 214, 215, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0889', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 216, 217, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0890', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 218, 219, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0891', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 221, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0892', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 256, 257, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0893', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 258, 259, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0894', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 260, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0895', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 270, 271, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0896', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 272, 273, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0897', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 272, 273, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1907-1908', N'折畳', NULL),
 ('F0898', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 274, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0899', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 299, NULL, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0900', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 300, 301, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0901', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 302, 303, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0902', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 304, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0903', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 314, 315, N'良好', N'Shanghai', N'Kiangsu Railway', 'M', N'Map', N'1908', N'折畳', NULL),
 ('F0904', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 314, 315, N'良好', N'Shanghai', N'Shanghai-Nanking Railway', 'M', N'Map', N'1908', N'折畳', NULL),
 ('F0905', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 322, 323, N'良好', N'Shanghai', N'Woosung Bars', 'G', N'グラフ', N'1908', N'折畳', NULL),
 ('F0906', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 332, 333, N'破損修理済', N'Shanghai', N'Horbour Administration', 'M', N'Map', N'1909', N'折畳', N'合成'),
('F0907', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 518, 519, N'良好', N'Canton', N'Canton Disctrict', 'M', N'Map', N'1909', N'折畳', NULL),
 ('F0908', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 602, 603, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0909', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 604, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0910', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 605, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0911', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 613, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0912', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 614, 615, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0913', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 616, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0914', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 617, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0915', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 669, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0916', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 670, 671, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0917', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 672, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0918', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 672, 673, N'良好', N'Lungchow', N'River Yangtze', 'G', N'グラフ', N'1905-1906', N'折畳', NULL),
 ('F0919', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 690, 691, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0920', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 692, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0921', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 707, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0922', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1908, NULL, 1, 708, 709, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0923', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 50, 51, N'良好', N'China', N'Shanghai Taels', 'G', N'グラフ', N'1907-1909', N'折畳', NULL),
 ('F0924', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 22, 23, N'折元破損', N'China', N'Postal Map of China', 'M', N'Map', N'1909', N'折畳', N'合成'),
('F0925', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 22, 23, N'破損修理済', N'Newchwang', N'奉天省城全圖', 'M', N'Map', N'1909', N'折畳', N'合成'),
('F0926', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 150, 151, N'折元破損', N'Chefoo', N'Eastern Shantung', 'M', N'Map', N'1909', N'折畳', NULL),
 ('F0927', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 195, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0928', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 196, 197, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0929', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 198, 199, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0930', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 200, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0931', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 206, 207, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0932', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 208, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0933', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 209, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0934', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 220, 221, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0935', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 222, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0936', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 223, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0937', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 244, 245, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0938', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 246, 247, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0939', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 248, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0940', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 248, 249, N'破損修理済', N'Yochow', N'River Yangtze', 'G', N'グラフ', N'1904-1909', N'折畳', NULL),
 ('F0941', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 249, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0942', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 258, 259, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0943', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 260, 261, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0944', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 262, 263, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0945', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 264, 265, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0946', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 266, 267, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0947', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 269, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0948', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 306, 307, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0949', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 308, 309, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0950', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 310, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0951', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 320, 321, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0952', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 322, 323, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0953', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 324, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0954', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 325, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0955', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 350, 351, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0956', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 350, 351, N'良好', N'Chinkiang', N'Trade Report', 'M', N'Map', NULL, NULL, NULL),
 ('F0957', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 352, 353, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0958', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 354, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0959', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 364, 365, N'良好', N'Shanghai', N'Shanghai Communication', 'M', N'Map', N'1909', N'折畳', NULL),
 ('F0960', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 366, 367, N'良好', N'Shanghai', N'Shanghai Taels', 'G', N'グラフ', N'1905-1909', NULL, NULL),
 ('F0961', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 376, 377, N'地僅かな破損', N'Shanghai', N'Woosung Bars', 'G', N'グラフ', N'1909', N'折畳', NULL),
 ('F0962', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 384, 385, N'良好', N'Shanghai', N'Horbour Administration', 'M', N'Map', N'1910', N'折畳', N'合成'),
('F0963', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 624, 625, N'良好', N'Kowloon', N'Canton and West River Deltas', 'M', N'Map', N'1909', N'折畳', NULL),
 ('F0964', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 640, 641, N'折元破損、端折れ', N'Lappa', N'Port of Heungchow', 'M', N'Map', N'1909', N'折畳', NULL),
 ('F0965', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 668, 669, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0966', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 670, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0967', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 671, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0968', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 679, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0969', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 680, 681, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0970', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 682, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0971', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 683, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0972', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 739, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0973', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 740, 741, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0974', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 760, 761, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0975', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 762, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0976', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 779, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0977', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1909, NULL, 1, 780, 781, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0978', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 42, 43, N'折元破損', N'China', N'Tonnage of Shipping', 'G', N'グラフ', N'1870-1910', N'折畳', N'合成'),
('F0979', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 52, 53, N'良好', N'China', N'Shanghai Taels', 'G', N'グラフ', N'1908-1910', N'折畳', NULL),
 ('F0980', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 46, 47, N'折元僅かな破損、端折れ', N'Lungchingtsun', N'Western Yenchi District', 'M', N'Map', N'1910', N'折畳', N'合成'),
('F0981', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 138, 139, N'折元破損、端折れ', N'Tientsin', N'China and Manchuria', 'M', N'Map', N'1910', N'折畳', NULL),
 ('F0982', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 219, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0983', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 220, 221, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0984', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 222, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0985', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 223, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0986', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 232, 233, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0987', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 234, 235, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0988', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 236, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0989', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 248, 249, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0990', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 250, 251, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0991', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 252, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0992', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 253, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0993', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 276, 277, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0994', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 278, 279, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0995', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 280, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F0996', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 289, NULL, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0997', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 290, 291, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0998', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 292, 293, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F0999', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 294, 295, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1000', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 296, 297, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1001', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 299, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1002', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 338, 339, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1003', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 340, 241, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1004', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 342, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1005', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 343, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1006', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 353, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1007', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 354, 355, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1008', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 356, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1009', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 356, 357, N'良好', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1908-1910', N'折畳', NULL),
 ('F1010', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 357, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1011', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 384, 385, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1012', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 386, 387, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1013', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 388, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1014', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 678, 679, N'良好', N'Lappa', N'Junk trade routes', 'M', N'Map', N'1910', N'折畳', NULL),
 ('F1015', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 694, 695, N'良好', N'Kongmoon', N'Sunning Railway Line', 'M', N'Map', N'1910', NULL, NULL),
 ('F1016', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 706, 707, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1017', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 708, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1018', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 709, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1019', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 717, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1020', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 718, 719, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1021', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 720, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1022', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 777, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1023', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 778, 779, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1024', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 799, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1025', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 800, 801, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1026', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 817, NULL, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1027', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1910, NULL, 1, 818, 819, N'良好', N'Yatung', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1028', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 58, 59, N'破損、端折れ', N'China', N'Postal Map of China', 'M', N'Map', N'1911', N'折畳', N'合成'),
('F1029', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 46, 47, N'良好', N'kirin', N'Sungari River', 'M', N'Map', N'1911', NULL, NULL),
 ('F1030', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 239, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1031', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 240, 241, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1032', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 242, 243, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1033', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 244, NULL, N'良好', N'Chungking', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1034', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 245, NULL, N'良好', N'Chungking', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1035', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 253, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1036', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 254, 255, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1037', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 256, NULL, N'良好', N'Ichang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1038', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 257, NULL, N'良好', N'Ichang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1039', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 270, 271, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1040', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 272, NULL, N'良好', N'Shasi', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1041', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 273, NULL, N'良好', N'Shasi', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1042', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 297, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1043', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 298, 299, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1044', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 300, NULL, N'良好', N'Yochow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1045', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 301, NULL, N'良好', N'Yochow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1046', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 310, 311, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1047', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 312, 313, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1048', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 314, 315, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1049', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 316, 317, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1050', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 318, 319, N'良好', N'Hankow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1051', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 321, NULL, N'良好', N'Hankow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1052', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 362, 363, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1053', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 364, 365, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1054', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 366, NULL, N'良好', N'Kiukiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1055', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 367, NULL, N'良好', N'Kiukiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1056', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 377, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1057', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 378, 379, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1058', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 380, NULL, N'良好', N'Wuhu', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1059', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 380, 381, N'折目に僅かな破損', N'Wuhu', N'River Yangtze', 'G', N'グラフ', N'1909-1911', N'折畳', NULL),
 ('F1060', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 381, NULL, N'良好', N'Wuhu', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1061', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 410, 411, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1062', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 410, 411, N'良好', N'Chinkiang', N'Chinkiang Harbour', 'M', N'Map', N'1861-1912', N'折畳', NULL),
 ('F1063', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 410, 411, N'良好', N'Chinkiang', N'Chinkiang Harbour', 'M', N'Map', N'1905-1912', N'折畳', NULL),
 ('F1064', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 412, 413, N'良好', N'Chinkiang', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1065', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 414, NULL, N'良好', N'Chinkiang', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1066', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 736, 737, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1067', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 738, NULL, N'良好', N'Samshui', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1068', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 739, NULL, N'良好', N'Samshui', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1069', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 747, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1070', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 748, 749, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1071', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 750, NULL, N'良好', N'Wuchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1072', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 751, NULL, N'良好', N'Wuchow', N'Shipping', 'G', N'グラフ', NULL, NULL, NULL),
 ('F1073', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 807, NULL, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1074', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 808, 809, N'良好', N'Lungchow', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1075', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 808, 809, N'良好', N'Lungchow', N'River Tso-Chiang', 'G', N'グラフ', N'1909-1911', N'折畳', NULL),
 ('F1076', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 831, NULL, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL),
 ('F1077', N'XVIII-F-6 Report on Trade at the treaty ports in China', 1911, NULL, 1, 832, 833, N'良好', N'Szemao', N'Trade Report', NULL, NULL, NULL, NULL, NULL);
 GO